services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: vehicle_db
    command: ["python", "run_duckdb.py"]
    volumes:
      - ./data/db:/app/data/db

  ingestion:
    build:
      context: ./ingestion
      dockerfile: Dockerfile
    container_name: ingestion
    command: ["python", "prepare_data.py"]
    volumes:
      - ./data:/app/data

  chunker:
    build:
      context: ./chunking
      dockerfile: Dockerfile
    container_name: chunker
    command: ["python", "make_chunks.py"]
    volumes:
      - ./data:/app/data

  embedding:
    build:
      context: ./embedding
      dockerfile: Dockerfile
    container_name: embedding
    command: ["python", "embed_chunks.py"]
    volumes:
      - ./data:/app/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data


