services:
  chunking:
    build:
      context: ./chunking
      dockerfile: Dockerfile
    container_name: chunking
    volumes:
      - ./data:/app/data
    command: ["true"]
    # chunkerは必要時に "docker compose run chunking python make_chunks.py" で実行

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: vehicle_db
    volumes:
      - ./data:/app/data
    command: python run_duckdb.py

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    command: uvicorn main:app --host 0.0.0.0 --port 8000


